# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.59.0
    hooks:
    -   id: golangci-lint
        name: golangci-lint
        description: "Fast linters runner for Go"
        entry: golangci-lint run --fix
        language: golang
        types: [go]
        additional_dependencies: []

-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    -   id: go-fmt
    -   id: go-imports
    -   id: go-vet
    -   id: go-clean
    -   id: go-mod-tidy

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md,mdx]
