name: Lint

on:
  push:
    branches: [ main, chore/setup-golangci-lint ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # Match your local Go version (run 'go version' locally to check)
          go-version: '1.22.x'  # Using .x to get the latest patch version
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: .
          only-new-issues: true
